

class Agent:
  fixed_questions:list[dict] = None
  models:dict = None

  def __init__(self, fixed_questions):
    self.fixed_questions = fixed_questions
    self.models = define_models()
  
  def forward(self, body: list[dict]) -> list[dict]:
    """
    Processes the input body and returns a response based on the agent's logic.

    Args:
        body (list[dict]): The input body containing user messages and other relevant information.

    Returns:
        list[dict]: The response generated by the agent.
    """
    # Here you would implement the logic to process the body and generate a response
    # For now, we will just return the fixed questions as a placeholder
    return self.fixed_questions



def define_models() -> dict:
  return